site_name: geoencoder
repo_url: https://github.com/ogoodwin505/geoencoder
site_url: https://ogoodwin505.github.io/geoencoder
site_description: Comparing the perforance of autoencoders to standard methods for dimension reduction of census data
site_author: Owen Goodwin
edit_uri: edit/main/docs/
repo_name: ogoodwin505/geoencoder
copyright: Maintained by <a href="https://ogoodwin505.com">ogoodwin505</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["geoencoder"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ogoodwin505/geoencoder
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/geoencoder

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
